# python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
work_dir: ../../data/st-gcn/xsub/with_rgb/rgb_tp15_tf5_

skeleton_joints_pkl: results/ntu60/xsub/joint_result_msg3d.pkl
skeleton_bones_pkl: results/ntu60/xsub/bone_result_msg3d.pkl

# feeder
feeder: feeder.feeder_rgb_fused_ntu.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: True
  temporal_rgb_frames: 5
  data_path: /media/bruce/2Tssd/data/ntu/xsub/train_data_joint.npy
  label_path: /media/bruce/2Tssd/data/ntu/xsub/train_label.pkl
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  temporal_rgb_frames: 5
  data_path: /media/bruce/2Tssd/data/ntu/xsub/val_data_joint.npy
  label_path: /media/bruce/2Tssd/data/ntu/xsub/val_label.pkl

# model
model: net.mmn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# training
temporal_positions: 15
fix_weights: True
joint_weights: models/ntu60/xsub/joint_model_stgcn.pt
device: [0,1,2,3]
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]
batch_size: 64
test_batch_size: 64
num_epoch: 80

# debug
debug: False
